ALTER TABLE PRODUCTS ALTER COLUMN RRP SET DATA TYPE NUMERIC(17,2);
ALTER TABLE PRODUCTS ALTER COLUMN PRICE_1 SET DATA TYPE NUMERIC(17,2);
ALTER TABLE PRODUCTS ALTER COLUMN PRICE_2 SET DATA TYPE NUMERIC(17,2);
ALTER TABLE PRODUCTS ALTER COLUMN PRICE_3 SET DATA TYPE NUMERIC(17,2);
ALTER TABLE PRODUCTS ALTER COLUMN PRICE_4 SET DATA TYPE NUMERIC(17,2);
ALTER TABLE PRODUCTS ALTER COLUMN PRICE_5 SET DATA TYPE NUMERIC(17,2);